### ISSUE TITLE
/claimlist console error and No display.

### ISSUE THREAD

**Issue by RustyDagger** [RoboMWM/ClaimlistClassifier#1]
Fresh install running very minimal plugins as just setting up.

I joined created two claims applied a name to both with /claimname then ran /claimlist it apears to just show the default Grief prevention print out. [Image showing /claimlist](http://prntscr.com/ihaoxd)

Wow Glad I checked just found this in console. names.data is saving the info fine it just seems to be the fech / display that's broken Thinking about it now Could deluxechat break this somehow?

```
[20:01:15 INFO]: RustyDagger issued server command: /claimname Test
[20:01:24 INFO]: RustyDagger issued server command: /claimlist
[20:01:24 ERROR]: Could not pass event PlayerCommandPreprocessEvent to ClaimslistClassifier v1.2.5
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-fd702e4]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-fd702e4]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fd702e4]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fd702e4]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1389) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fd702e4]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fd702e4]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fd702e4]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fd702e4]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fd702e4]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_121]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fd702e4]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fd702e4]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fd702e4]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fd702e4]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fd702e4]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.IllegalAccessError: tried to access method me.ryanhamshire.GriefPrevention.GriefPrevention.sendMessage(Lorg/bukkit/entity/Player;Lorg/bukkit/ChatColor;Lme/ryanhamshire/GriefPrevention/Messages;[Ljava/lang/String;)V from class me.robomwm.claimslistclassifier.command.ClaimsListCommand
        at me.robomwm.claimslistclassifier.command.ClaimsListCommand.onCommand(ClaimsListCommand.java:80) ~[?:?]
        at me.robomwm.claimslistclassifier.ClaimslistClassifier.interceptClaimsListCommand(ClaimslistClassifier.java:98) ~[?:?]
        at me.robomwm.claimslistclassifier.ClaimslistClassifier.onPlayerPreprocess(ClaimslistClassifier.java:107) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-fd702e4]
        ... 16 more
```

**Comment by RoboMWM** [comment]
Ooof, pls format better. Look at my edit.

**Comment by RoboMWM** [comment]
This addon currently requires a dev build of GP, which can be found in one of the releases here.

(Partly a reason why it's still unreleased. Also hope you're considering [patreon](https://patreon.com/RoboMWM) thx.)
