### ISSUE TITLE
Error naming a admin claim

### ISSUE THREAD

**Issue by Blackmadman** [RoboMWM/ClaimlistClassifier#19]
Is there a chance that the plugin will be updated? With the current GP version and Minecraft 1.21 I get this error message when I try to name a admin claim:

[10:48:22 ERROR]: Command exception: /nameclaim Startgebiet
org.bukkit.command.CommandException: Unhandled exception executing command 'nameclaim' in plugin ClaimslistClassifier v1.6
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:446) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.commands.Commands.performCommand(Commands.java:353) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.commands.Commands.performCommand(Commands.java:340) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.commands.Commands.performCommand(Commands.java:335) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2147) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2121) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1478) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1456) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1449) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1408) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1415) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1260) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.UUID.equals(Object)" because "claim.ownerID" is null
        at claimslistclassifier.jar/com.robomwm.claimslistclassifier.command.NameClaimCommand.onCommand(NameClaimCommand.java:48) ~[claimslistclassifier.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        ... 27 more

**Comment by Blackmadman** [comment]
I tried a bit more and found out the following:

1. the error message above only appears when I try to give an admin claim a name.
2. if I give a normal player claim a name, no error message comes up, the plugin says that the claim now has the name but when I use /claimlist, no names are displayed, only the normal claim list with the world and the coordinates of the claim. There is also no error in the log.
3. if I set claimListSorting: from false to true in config.yml, no more claims are displayed with /claimlist, only the blocks you have. No error message in the console or in the log.
4. if I set ClickableClaimslist: false to true in config.yml, nothing happens, nothing can be clicked. Again, there is no error message in the console or in the log.

The file names.data is created and when I name a claim, the claim number and name are also entered there. Apparently, however, they are not read or simply not displayed.

What works is the confirmation prompt for the /abandonclaim command and the /trustedclaimlist command.

**Comment by RoboMWM** [comment]
It seems I did indeed forget to account for administrative claims when doing a check to see if the player owned the claim they're trying to name. That I can fix. If you can break out this specific issue (which is what the error in the original post is), or make separate issue(s) for the other things I'll be more likely to remember to fix this. That being said, I don't think I attempt to intecept /adminclaimslist as far as I'm aware, and that would technically be a new feature.

I know I try to intercept the /claimslist command from GP, and I think I use spigot's json/chat api- which I'm not sure how paper deals with that since they don't like spigot's implementation and have their own api from what I've heard.

I wonder if the plugin still functions properly on spigot itself?

**Comment by Blackmadman** [comment]
I can create separate error messages for the other 3 problems, no problem.
Unfortunately, I can't say whether the plugin still works under Spigot. Everyone I know who used Spigot has since switched to Paper because the performance and stability of Paper is simply better. And I myself have never used Spigot for my server. So I don't know anything about Spigot as an admin, only as a player that the servers often crashed :D
