### ISSUE TITLE
Typed the command incorrectly and found this exception.

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/ClaimlistClassifier#9]
```
21.03 00:57:09 [Server] WARN Unexpected exception while parsing console command "claimexpire delay  -60"
21.03 00:57:09 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'claimexpire' in plugin ClaimslistClassifier v1.5
21.03 00:57:09 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-561]
21.03 00:57:09 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-561]
21.03 00:57:09 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[patched_1.13.2.jar:git-Paper-561]
21.03 00:57:09 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:696) ~[patched_1.13.2.jar:git-Paper-561]
21.03 00:57:09 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.handleCommandQueue(DedicatedServer.java:483) ~[patched_1.13.2.jar:git-Paper-561]
21.03 00:57:09 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:440) ~[patched_1.13.2.jar:git-Paper-561]
21.03 00:57:09 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-561]
21.03 00:57:09 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-561]
21.03 00:57:09 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
21.03 00:57:09 [Server] INFO Caused by: java.lang.IllegalArgumentException: Name cannot be empty
21.03 00:57:09 [Server] INFO at org.apache.commons.lang.Validate.notEmpty(Validate.java:321) ~[patched_1.13.2.jar:git-Paper-561]
21.03 00:57:09 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.getOfflinePlayer(CraftServer.java:1449) ~[patched_1.13.2.jar:git-Paper-561]
21.03 00:57:09 [Server] INFO at com.robomwm.claimslistclassifier.command.ClaimExpireCommand.getPlayer(ClaimExpireCommand.java:53) ~[?:?]
21.03 00:57:09 [Server] INFO at com.robomwm.claimslistclassifier.command.ClaimExpireCommand.onCommand(ClaimExpireCommand.java:83) ~[?:?]
21.03 00:57:09 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.2.jar:git-Paper-561]
21.03 00:57:09 [Server] INFO ... 8 more
```

**Comment by RoboMWM** [comment]
weird, I guess console doesn't strip out extra spaces like the client (or server validating client?) does when sending a message.

Since I made some stupid algorithm to attempt to find a player's name if the expected arguments exceed the required parameters, this isn't necessarily an easy fix, unless I redo the commands for this feature. Which for this one, there are only two, so if you're okay with that I can do that.

**Comment by NullCase** [comment]
Isn't necessarily easy.

I'm OK with leaving it, at least for now.

**Comment by RoboMWM** [comment]
Leaving as this unless the issue's scope becomes more widespread I guess.
